### ISSUE TITLE
Invalid return value on first run of every getter function

### ISSUE THREAD

**Issue by KaoruNishikawa** [ogawa-ros/ogameasure#12]
https://github.com/ogawa-ros/ogameasure/blob/master/ogameasure/device/Phasematrix/QuickSyn_FSW0000.py

**Comment by YuichiHori** [comment]
`socket.makefile()`で生成されたファイルオブジェクトは`socket.close()`の前に`sockfp.close()`で閉じる必要があるかも
https://docs.python.org/ja/3/library/socket.html#socket.socket.makefile

**Comment by YuichiHori** [comment]
`query`の関数内で`send`と`recv`や`readline`の間に数ms程度の待ち時間が必要
